/* =========================================================
   SUPABASE AUTOGENERATED & CURATED TYPESCRIPT CONTRACTS (Step 20)
   Single source of truth for PostgreSQL schema & RPC payloads
   ========================================================= */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      families: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          created_by: string;
          family_code: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          created_by: string;
          family_code: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          created_by?: string;
          family_code?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      family_members: {
        Row: {
          id: string;
          family_id: string;
          user_id: string;
          role: string;
          status: 'active' | 'pending' | 'removed';
          joined_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          user_id: string;
          role?: string;
          status?: 'active' | 'pending' | 'removed';
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          user_id?: string;
          role?: string;
          status?: 'active' | 'pending' | 'removed';
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      family_join_requests: {
        Row: {
          id: string;
          family_id: string;
          user_id: string;
          status: 'pending' | 'approved' | 'rejected';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          user_id: string;
          status?: 'pending' | 'approved' | 'rejected';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          user_id?: string;
          status?: 'pending' | 'approved' | 'rejected';
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          family_id: string | null;
          type: string;
          title: string;
          message: string;
          data: Json;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          family_id?: string | null;
          type?: string;
          title: string;
          message: string;
          data?: Json;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          family_id?: string | null;
          type?: string;
          title?: string;
          message?: string;
          data?: Json;
          is_read?: boolean;
          created_at?: string;
        };
      };
    };
    Functions: {
      create_family: {
        Args: {
          p_name: string;
          p_description?: string;
          p_family_code?: string;
        };
        Returns: Json;
      };
      request_to_join_family: {
        Args: {
          p_family_code: string;
        };
        Returns: Json;
      };
      approve_family_join_request: {
        Args: {
          p_request_id: string;
        };
        Returns: Json;
      };
      reject_family_join_request: {
        Args: {
          p_request_id: string;
        };
        Returns: Json;
      };
    };
  };
}
